Repository systopia/de.systopia.twingle, pull requests merged in 2024-04, with the labels that each got.

#66 Extend custom field mapping
  api/v3/TwingleDonation/Submit.php
Labels: enhancement, status:reviewed and tested

#73 Identify profiles by ID
  CRM/Twingle/Form/Profile.php
  CRM/Twingle/Form/Settings.php
  CRM/Twingle/Page/Profiles.php
  CRM/Twingle/Profile.php
  templates/CRM/Twingle/Page/Profiles.tpl
Labels: enhancement, status:needs review

#75 Improve profile validation
  CRM/Twingle/Form/Profile.php
  CRM/Twingle/Profile.php
  Civi/Twingle/Exceptions/BaseException.php
  Civi/Twingle/Exceptions/ProfileValidationError.php
Labels: enhancement, status:reviewed and tested

#74 Improve default profile behavior
  CRM/Twingle/Form/Profile.php
  CRM/Twingle/Page/Profiles.php
  CRM/Twingle/Profile.php
  templates/CRM/Twingle/Form/Profile.tpl
Labels: enhancement, status:needs review

#76 Improve profile list view
  CRM/Twingle/Page/Profiles.php
  css/twingle.css
  templates/CRM/Twingle/Page/Profiles.tpl
Labels: enhancement, status:needs review

#68 Add generic payment method
  CRM/Twingle/Form/Profile.php
  CRM/Twingle/Profile.php
Labels: enhancement, status:needs work
