Repository systopia/de.systopia.twingle, pull requests merged in 2024-06, with the labels that each got.

#90 Do not require project IDs for default profile forms
  CRM/Twingle/Form/Profile.php
Labels: enhancement, status:reviewed and tested

#91 Repair help links in settings form
  templates/CRM/Twingle/Form/Settings.tpl
Labels: bug, status:reviewed and tested

#88 Improve profile options for note creation
  CRM/Twingle/Form/Profile.php
  CRM/Twingle/Profile.php
  CRM/Twingle/Upgrader.php
  api/v3/TwingleDonation/Submit.php
  l10n/de_DE/LC_MESSAGES/twingle.mo
  l10n/de_DE/LC_MESSAGES/twingle.po
  l10n/pot/twingle.pot
  templates/CRM/Twingle/Form/Profile.hlp
  templates/CRM/Twingle/Form/Profile.tpl
Labels: enhancement, status:reviewed and tested

#94 Add the organisation instead of the individual to donation receipts group
  api/v3/TwingleDonation/Submit.php
Labels: bug, status:reviewed and tested

#92 Some more fixed conditions
  CRM/Twingle/Form/Profile.php
  CRM/Twingle/Submission.php
  CRM/Twingle/Tools.php
  api/v3/TwingleDonation/Submit.php
Labels: bug, status:reviewed and tested

#93 Improve API result values
  api/v3/TwingleDonation/Submit.php
Labels: enhancement, status:needs review
